name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Publish
      run: dotnet publish --runtime linux-x64 --configuration Release /p:Platform=x64

    - name: Prepare cleanup script
      run: chmod +x ./build/cleanup.sh
        ./build/cleanup.sh
        
    - name: run cleanup script
      run: ./build/cleanup.sh
        
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ftp_server_host }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        port: ${{ secrets.ftp_port }}
        source: 'KurdishCelebs.WebApp/bin/x64/Release/netcoreapp3.1/linux-x64/publish'
        target: ${{ secrets.ftp_dest_path }}
        rm: true
        strip_components: 6
  
    - name: Run update script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ftp_server_host }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        port: ${{ secrets.ftp_port }}
        script: ${{ secrets.update_script_path }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: 'webapp'
        # Directory containing files to upload
        path: 'KurdishCelebs.WebApp/bin/x64/Release/netcoreapp3.1/linux-x64/publish'
    
